# Generated by Django 5.1 on 2024-08-22 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pid', models.BigAutoField(primary_key=True, serialize=False)),
                ('major', models.CharField(blank=True, max_length=150, null=True)),
                ('resume', models.TextField(blank=True, null=True)),
                ('title', models.SmallIntegerField(choices=[(0, '无'), (1, '教授'), (2, '研究员'), (3, '副教授'), (4, '副研究员'), (5, '讲师'), (6, '助理研究员')], default=0)),
                ('degree', models.SmallIntegerField(choices=[(0, '无'), (1, '博士'), (2, '硕士'), (3, '学士')], default=0)),
                ('position', models.SmallIntegerField(choices=[(0, '无'), (1, '教职工'), (2, '博士后'), (2, '学生')], default=0)),
                ('status', models.SmallIntegerField(choices=[(0, '无'), (1, '在职'), (2, '离职'), (3, '在读'), (4, '毕业'), (5, '退学')], default=0)),
                ('group', models.SmallIntegerField(choices=[(0, '未激活'), (1, '访客'), (2, '编辑'), (3, '管理员')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
