# Generated by Django 5.1 on 2024-08-22 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('specimen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_en', models.CharField(max_length=100)),
                ('species_cn', models.CharField(blank=True, max_length=100)),
                ('kingdom_en', models.CharField(blank=True, max_length=30)),
                ('kingdom_cn', models.CharField(blank=True, max_length=30)),
                ('phylum_en', models.CharField(blank=True, max_length=30)),
                ('phylum_cn', models.CharField(blank=True, max_length=30)),
                ('class_en', models.CharField(blank=True, max_length=30)),
                ('class_cn', models.CharField(blank=True, max_length=30)),
                ('oder_en', models.CharField(blank=True, max_length=50)),
                ('oder_cn', models.CharField(blank=True, max_length=50)),
                ('family_en', models.CharField(blank=True, max_length=50)),
                ('family_cn', models.CharField(blank=True, max_length=50)),
                ('genus_en', models.CharField(blank=True, max_length=50)),
                ('genus_cn', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='pid',
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('details', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('ftype', models.SmallIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('tissue', models.CharField(blank=True, max_length=30)),
                ('collect_location', models.CharField(blank=True, max_length=200)),
                ('collect_longitude', models.CharField(blank=True, max_length=20)),
                ('collect_latitude', models.CharField(blank=True, max_length=20)),
                ('collect_time', models.DateField(blank=True)),
                ('store_place', models.CharField(max_length=100)),
                ('store_method', models.CharField(max_length=100)),
                ('comment', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.species')),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('gender', models.SmallIntegerField(choices=[(0, '无'), (1, '雄性'), (2, '雌性')], default=0)),
                ('bottle', models.CharField(blank=True, max_length=30)),
                ('details', models.TextField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specimen.species')),
            ],
        ),
        migrations.CreateModel(
            name='SampleMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='specimen.project')),
                ('sample', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='specimen.sample')),
                ('specimen', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='specimen.specimen')),
            ],
        ),
    ]
