# Generated by Django 5.1 on 2024-08-23 11:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0002_species_remove_profile_pid_profile_id_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='file',
            new_name='upfile',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='ftype',
            new_name='uptype',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='object_id',
        ),
        migrations.AddField(
            model_name='resource',
            name='uptime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='collect_people',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='files',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sample',
            name='photos',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
