# Generated by Django 5.1 on 2024-08-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0003_rename_file_resource_upfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='coolect_altitude',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sample',
            name='type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
