# Generated by Django 5.1 on 2024-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0004_sample_coolect_altitude_sample_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='code',
            new_name='sample_code',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='name',
            new_name='sample_name',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='tissue',
            new_name='sample_tissue',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='type',
            new_name='sample_type',
        ),
        migrations.AlterField(
            model_name='sample',
            name='files',
            field=models.JSONField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sample',
            name='photos',
            field=models.JSONField(blank=True, default=''),
        ),
    ]
