# Generated by Django 5.1 on 2024-08-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0005_rename_code_sample_sample_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='coolect_altitude',
            new_name='collect_altitude',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='collect_time',
            new_name='collect_date',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='files',
        ),
        migrations.AddField(
            model_name='sample',
            name='attachments',
            field=models.JSONField(blank=True, default=[]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='photos',
            field=models.JSONField(blank=True, default=[]),
        ),
    ]
