# Generated by Django 5.1 on 2024-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specimen', '0006_rename_coolect_altitude_sample_collect_altitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='collect_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='store_method',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sample',
            name='store_place',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
